version: '3'
services:
  rdflib-endpoint:
    container_name: translator-sparql-service
    build: .
    restart: unless-stopped
    environment: 
      # Use reverse nginx-proxy https://github.com/nginx-proxy/nginx-proxy
      VIRTUAL_HOST: translator-service.137.120.31.102.nip.io
      LETSENCRYPT_HOST: translator-service.137.120.31.102.nip.io
      VIRTUAL_PORT: 80
    # ports:
    #   - 8000:80

